### ISSUE TITLE
A custom component that can execute other components in parallel

### ISSUE THREAD

**Issue by dingusagar** [RasaHQ/rasa-nlu-examples#138]
Currently all the components in nlu execute in a sequential manner. But many a times, a couple of components can be executed in parallel. 

For eg, DucklingEntityExtracter and another custom component like SentimentClassifier can be executed parallely since there is no dependency between them. 

This way can we bring down the overall prediction time ?

**Comment by sara-tagger** [comment]
Thanks for the issue, @desmarchris will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by koaning** [comment]
Theoretically, this could indeed happen in parallel. But the question is if the parallelism overhead is worth it. You will need to start a pool of resources that is tasked with tracking tasks in queues. 

Another practicality is that we don't know upfront what the entity models require. Maybe they only need a tokenizer, maybe they require some features as well, and ... technically, they may also depend on the output of the intent classifier.

**Comment by koaning** [comment]
You're free to explore and benchmark the idea if you're interested, but for sake of simplicity, I'd prefer to simply stick to the pipeline implementation inside of Rasa. The goal of this repo is to contribute components that are compatible with the latest Rasa version, not to overwrite main implementations inside of Rasa.
