### ISSUE TITLE
Numpy incomptaible version due Tensorflow dependency conflit using Pipenv

### ISSUE THREAD

**Issue by guillaumecostanza** [RasaHQ/rasa-nlu-examples#147]
Hi there !

First of all thank you for the amazing job you do !

Here is my problem, I use pipenv as package manager and i have the following incompatibilty with numpy : 

```
There are incompatible versions in the resolved dependencies:
  numpy (from bpemb==0.3.3->-r /tmp/pipenvrqgb4b03requirements/pipenv-_19jh_yy-constraints.txt (line 3))
  numpy<1.19,>=1.16 (from rasa==2.8.7->-r /tmp/pipenvrqgb4b03requirements/pipenv-_19jh_yy-constraints.txt (line 4))
  numpy>=1.11.3 (from gensim==3.8.3->-r /tmp/pipenvrqgb4b03requirements/pipenv-_19jh_yy-constraints.txt (line 2))
  numpy>=1.17.3 (from pandas==1.3.3->-r /tmp/pipenvrqgb4b03requirements/pipenv-_19jh_yy-constraints.txt (line 6))
  numpy~=1.19.2 (from tensorflow==2.4.3->-r /tmp/pipenvrqgb4b03requirements/pipenv-_19jh_yy-constraints.txt (line 5))
```

I'm not a specialist of python but I guess that bumping tensorflow version would solve the problem ?

My pipfile 

```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
rasa = "==2.8.*"
rasa-nlu-examples = {git = "https://github.com/RasaHQ/rasa-nlu-examples", extras = ["fasttext"]}

[requires]
python_version = "3.7"
```

**Comment by guillaumecostanza** [comment]
As workaround, explicity using this tensorflow version works :

`tensorflow = "==2.3.*"
`

**Comment by koaning** [comment]
The workaround will hopefully suffice for now. I'd love to duve deeper into version issues but with the advent of Rasa 3.0 happening at some point this year I'd prefer to wait until that's released to double-check versions. 

I gotta ask, is there a reason you prefer to use fasttext as opposed to the bytepair embeddings? Also; what language are you exploring?

**Comment by koaning** [comment]
Am closing this issue due to radio silence but also with the advent of changes to our TensorFlow dependency, described [here](https://rasa.com/blog/let-s-talk-about-tensorflow-2-6/).
