### ISSUE TITLE
Tokenizers for Less Common Languages

### ISSUE THREAD

**Issue by koaning** [RasaHQ/rasa-nlu-examples#15]
The whitespace tokenizer in Rasa is focussed on western languages. If there are languages who appreciate a different tokenizer then we might explore alternatives in this thread.

**Comment by koaning** [comment]
Some languages will be added via this PR; https://github.com/RasaHQ/rasa-nlu-examples/pull/30.

**Comment by tttthomasssss** [comment]
PR #35 adds tokenisation support for Thai

**Comment by koaning** [comment]
Will split this issue up into issues per tool we'd like to add.
