### ISSUE TITLE
Unclear error message when file is not found

### ISSUE THREAD

**Issue by tttthomasssss** [RasaHQ/rasa-nlu-examples#16]
Currently when the `file` is not found at the specified `cache_dir` in the `config.yml` file, the error message is very opaque:

```
ValueError: /path/to/file/wiki.es.bin cannot be opened for loading!
```

The problem was that the file `wiki.es.bin` does not exist at `/path/to/file`, though this is not at all obvious from the error message.

**Comment by koaning** [comment]
This was confirmed on FastText embeddings but should also be checked for the BytePair ones.

**Comment by tttthomasssss** [comment]
Looks like the `BytePairFeaturizer` ignores the `cache_dir` and `file` opts - at least when `vs` and `dim` are specified.

**Comment by koaning** [comment]
That ... should also not happen. Noted for a fix!
