### ISSUE TITLE
Cached Usage of SparseBytePairFeaturizer docs contains dense BytePairFeaturizer

### ISSUE THREAD

**Issue by namhoai167** [RasaHQ/rasa-nlu-examples#161]
The [Cached Usage](https://rasahq.github.io/rasa-nlu-examples/docs/featurizer/sparse_bytepair/#cached-usage) of SparseBytePairFeaturizer contains dense BytePairFeaturizer. I checked the [sparse_bytepair.md](https://github.com/RasaHQ/rasa-nlu-examples/blob/main/docs/docs/featurizer/sparse_bytepair.md#cached-usage) and it is with SparseBytePairFeaturizer. There was a [commit](https://github.com/RasaHQ/rasa-nlu-examples/commit/9b81e706b464e731445031a48e5ee83a8866a125) edit this but it's not showing on the docs.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @alopez will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by koaning** [comment]
That's a fair comment! 

One thing though; are you using the sparse BytePair featurizer? I'm currently prepping the repository for Rasa 3.0 and my impression was that the feature was barely used and I was considering dropping it. Would you happen to have an anecdote that suggests that I should keep it around?

**Comment by namhoai167** [comment]
Thank @koaning for your reply, you and Dr. Rachael are the two who teach me most of the stuff about NLP from Jan and till now. I'm not using sparse BytePair featurizer at the moment and you can drop it if you want. I came from your videos ([this](https://www.youtube.com/watch?v=Ju7l5ADg10U&list=PL75e0qA87dlG-za8eLI6t0_Pbxafk-cxb&index=18), [this](https://www.youtube.com/watch?v=kNw9dpzp5RU&list=PL75e0qA87dlG-za8eLI6t0_Pbxafk-cxb&index=19) and [this](https://www.youtube.com/watch?v=-0IjF-7OB3s&list=PL75e0qA87dlG-za8eLI6t0_Pbxafk-cxb&index=21)), so CountVectorsFeaturizer is doing a great job at handling spelling errors, but I want to try stacking a subword featurizer (which is dense BytePair) and benchmark will it increase DIET classification score on my small artificial errors data. 
For sparse BytePair featurizer, I'm not sure how it works. It has terminologies that I don't know like BytePair tokeniser, I try to figure out is it BPE tokenizer or something else. After well understand it, I may give it a shot.

**Comment by koaning** [comment]
Happy to hear it that you find our content useful :) 

I will drop the sparse featurizer then, which will also resolve this issue.
