### ISSUE TITLE
Implementation 

### ISSUE THREAD

**Issue by Munirah-kh** [RasaHQ/rasa-nlu-examples#162]
Hello 
I have code for rasa chatbot in English language but, when i run the code for Arabic language there is an error 
So could u please tell me how to integrate the code u provided with the steps to train and run the chatbot for Arabic language 
Thank you

**Comment by koaning** [comment]
Could you share the Arabic `config.yml` file that you tried? 

I think the standard pipeline that comes with `rasa init` theoretically should be a reasonable baseline. Arabic is whitespace-separated, right?

**Comment by Munirah-kh** [comment]
[](url)yes its whitespace-separated
and the error i got is this:
**InvalidModelError: Model 'ar' is not a linked spaCy model.  Please download and/or link a spaCy model, e.g. by running:
python -m spacy download en_core_web_md
python -m spacy link en_core_web_md en**
 _error with "ar"_

![config file](https://user-images.githubusercontent.com/67229139/150147837-dd070005-2dd2-473a-8af5-3374f166f891.png)

**Comment by koaning** [comment]
What version of python/Rasa are you using? 

Also, please refrain from using screenshots to share code. Screenshots cannot be copied/pasted/indexed/searched.

**Comment by Munirah-kh** [comment]
Python: 3.6.8
rasa Version: 2.3.0
CODE:
---
language: ar 
pipeline:
  - name: "SpacyNLP"
  - name: "SpacyTokenizer"
  - name: "SpacyFeaturizer"
  - name: "RegexFeaturizer"
  - name: "CRFEntityExtractor"
  - name: "EntitySynonymMapper"
  - name: "SklearnIntentClassifier"
  - name: WhitespaceTokenizer
#  - name: RegexFeaturizer
#  - name: LexicalSyntacticFeaturizer
#  - name: CountVectorsFeaturizer
#  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true
    model_confidence: cosine
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
    constrain_similarities: true
    model_confidence: cosine
policies:
  - name: RulePolicy
  - name: MemoizationPolicy
    max_history: 3
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true
    model_confidence: cosine

**Comment by Munirah-kh** [comment]
Python: 3.6.8
rasa Version: 2.3.0
Code:
language: ar 
pipeline:
   name: "SpacyNLP"
   name: "SpacyTokenizer"
   name: "SpacyFeaturizer"
   name: "RegexFeaturizer"
   name: "CRFEntityExtractor"
   name: "EntitySynonymMapper"
   name: "SklearnIntentClassifier"
   name: WhitespaceTokenizer
#   name: RegexFeaturizer
#   name: LexicalSyntacticFeaturizer
#   name: CountVectorsFeaturizer
#   name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  name: DIETClassifier
    epochs: 100
    constrain_similarities: true
    model_confidence: cosine
   name: EntitySynonymMapper
   name: ResponseSelector
    epochs: 100
    constrain_similarities: true
    model_confidence: cosine
policies:
   name: RulePolicy
   name: MemoizationPolicy
    max_history: 3
   name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true
    model_confidence: cosine

**Comment by Munirah-kh** [comment]
Python: 3.6.8
rasa Version: 2.3.0

**Comment by Munirah-kh** [comment]
this is an example of Arabic language : مرحبا بكم 
how can i install whitespace tokenizer ?

**Comment by Munirah-kh** [comment]
Ok I’ll try it and reply back 
Thank you

**Comment by koaning** [comment]
I'll close the issue in the meantime since this question isn't about this repository. 

For future help, please add a ticket on our forum: https://forum.rasa.com.
