### ISSUE TITLE
rasa version error

### ISSUE THREAD

**Issue by AYUSH27112021** [RasaHQ/rasa-nlu-examples#172]
when i try to use pip install, i get the following error 
ERROR: Could not find a version that satisfies the requirement rasa~=3.0.0 (from rasa-nlu-examples)

**Comment by hack-r** [comment]
it looks like this thing is incompatible with 3.5.x

for me it automatically downgraded everything...

and there are no examples for 3.5.x?

**Comment by AYUSH27112021** [comment]
yup i got that to for this to work python version must be 3.7 or 3.8

**Comment by hack-r** [comment]
Glad to hear you got it working! Apologies for the confusion
- I was talking about the Rasa version (3.5.1). My Python version is 3.8.
