### ISSUE TITLE
Support 2.0

### ISSUE THREAD

**Issue by uncle-tony** [RasaHQ/rasa-nlu-examples#46]
Are you going to adapt examples to 2.0 version?

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @rctatman will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by koaning** [comment]
Yes! I might get started on that this week. I'd prefer to wait just a bit longer until the first patch release is out but the goal of this repository is to support the latest Rasa version.

**Comment by koaning** [comment]
There's a PR that's looking green. I'm waiting for my colleagues to review.

**Comment by koaning** [comment]
This should be fixed now. Feel free to post any bugs.
