### ISSUE TITLE
Confirm WhiteSpaceTokenizer for Arabic

### ISSUE THREAD

**Issue by koaning** [RasaHQ/rasa-nlu-examples#63]
I'm wondering if the issue [here](https://github.com/mpcabd/python-arabic-reshaper) isn't propagated to our WhitespaceTokenizer. It'd be good to confirm it's not an issue.

**Comment by AMR-KELEG** [comment]
I would be glad to help but I don't think this problem happens with Unicode python strings.
It generally happens on generating images like wordclouds (e.g: https://amueller.github.io/word_cloud/auto_examples/arabic.html)

**Comment by koaning** [comment]
yeah it seems to be an issue that the whatlies packages suffers from more than here. i wanted to double check but if you confirm it's fine ill gladly take your word for it :)
