### ISSUE TITLE
Turkish NLU data

### ISSUE THREAD

**Issue by merveenoyan** [RasaHQ/rasa-nlu-examples#98]
I'd like to add Turkish NLU data if there isn't anyone else doing it at the moment.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @kalkbrennerei will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by koaning** [comment]
Just to check, the NLU data ... are you referring to the names in this repository or the [NLU training data repository](https://github.com/RasaHQ/NLU-training-data)?
