### ISSUE TITLE
Remove occurrences of `token_pattern` parameter from `CountVectorFeaturizer` config

### ISSUE THREAD

**Issue by koernerfelicia** [RasaHQ/rasa-nlu-examples#99]
As per the discussion on Slack [here](https://rasa-hq.slack.com/archives/C8LEHMTAM/p1612351703357400) (summary: we've decided against exposing `token_pattern` and use `analyzer` instead) we should remove these occurrences and replace them with the appropriate `analyzer` argument (found in [benchmarking.md](https://github.com/RasaHQ/rasa-nlu-examples/blob/main/docs/benchmarking.md) and `readme.md`)

**Comment by koernerfelicia** [comment]
Related: https://github.com/RasaHQ/rasa/issues/8005

**Comment by koaning** [comment]
Just to check, is this an issue for this repo or for the main Rasa one? I don't think we're hosting countvector featurizers here.

**Comment by koernerfelicia** [comment]
For both! Sorry if it wasn't clear.

I had an issue to investigate whether we'd like to add this parameter, and we decided against it, so I wanted to cleanup any mentions of it as a configurable parameter. I can assign this to myself if you're in agreement.

**Comment by koaning** [comment]
Ah, I didn't know we mentioned the `token_pattern ` feature explicitly in the docs here. Feel free to remove any if you see 'em.
